# Keybinds

bind-key -n M-t new-window # Open new window
bind-key -n M-r command-prompt -I "" "rename-window '%%'" # Rename current window
bind-key -n M-w kill-window # Close current window
bind-key -n M-1 select-window -t 0 # Go to window 1
bind-key -n M-2 select-window -t 1 # Go to window 2
bind-key -n M-3 select-window -t 2 # Go to window 3
bind-key -n M-4 select-window -t 3 # Go to window 4
bind-key -n M-5 select-window -t 4 # Go to window 5
bind-key -n M-6 select-window -t 5 # Go to window 6
bind-key -n C-PageUp previous-window # Go to previous window
bind-key -n C-PageDown next-window # Go to next window
bind-key -n C-S-PageUp swap-window -t -1\; select-window -t -1 # Move window to lef
bind-key -n C-S-PageDown swap-window -t +1\; select-window -t +1 # Move window to right
bind-key -n M-d split-window -h -c '#{pane_current_path}' \; split-window -h -c '#{pane_current_path}' \; select-layout even-horizontal # Split window in 3 panes in the current path and spread them evenly
bind-key -n M-z resize-pane -Z # Zoom pane

# Go to previous pane, preventing loop
# If is zoomed, unzoom+zoom
# because a zoomed pane is considered the leftmost pane
bind-key -n M-h if -F '#{window_zoomed_flag}' {
  resize-pane -Z
  if -F '#{pane_at_left}' '' 'select-pane -L'
  resize-pane -Z
} {
  if -F '#{pane_at_left}' '' 'select-pane -L'
}

# Go to next pane, preventing loop
# If is zoomed, unzoom+zoom,
# because a zoomed pane is considered the rightmost pane
bind-key -n M-l if -F '#{window_zoomed_flag}' {
  resize-pane -Z
  if -F '#{pane_at_right}' '' 'select-pane -R'
  resize-pane -Z
} {
  if -F '#{pane_at_right}' '' 'select-pane -R'
}


# Design tweaks

### Status bar
set -g status-position top
set -g status-style 'bg=black'
set -g status-left ''
set -g status-right ''

### Active window
setw -g window-style 'bg=#13141c fg=default'
setw -g window-active-style 'bg=#1a1b26 fg=default'
setw -g window-status-current-style 'bg=white fg=black'
setw -g window-status-current-format ' #W '

### Other windows
setw -g window-status-style 'bg=black fg=white dim'
setw -g window-status-format ' #W '


# Tweaks

### Prevent slow Esc inside Neovim
set -sg escape-time 0

### Enable mouse
set -g mouse on

### Focus events for Neovim
set-option -g focus-events on

### Fix colors for Neovim inside tmux
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:Tc"
